###Look table
GET http://localhost:8000/users

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "lastname": "Dupont",
    "firstname": "",
    "ordinal_number": "48545",
    "adress": "toto"
}

###
PUT http://localhost:8000/users/9
Content-Type: application/json

{
    "ordinal_number": "211"
}

###
DELETE http://localhost:8000/users/4