###Look table
GET http://localhost:8000/users

###
GET http://localhost:8000/users/3

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "lastname": "Dupont",
    "firstname": "",
    "ordinal_number": "48545",
    "adress": "toto"
}

###
PUT http://localhost:8000/users/lo
Content-Type: application/json

{
    "ordinal_number": "25100"
}

###
DELETE http://localhost:8000/users/9



#####################################################################################



###Look all activities
GET http://localhost:8000/activities

###Look one activity
GET http://localhost:8000/activities/2


### POST Add one activity
POST http://localhost:8000/activities
Content-Type: application/json

{
    "title": "Echographie",
    "description": "L'échographie est une technique d'imagerie employant des ultrasons."
}

### PUT Change one activity
PUT http://localhost:8000/activities/1
Content-Type: application/json

{
    "title": "Médecine générale",
    "description": "Lorem ipsum"
}

###DELETE one activity
DELETE http://localhost:8000/activities/1


####################################################################################


###Look all PurchasesOrders
GET http://localhost:8000/purchasesorders

###Look one PurchasesOrders
GET http://localhost:8000/purchasesorders/1