###Look table
GET http://localhost:8000/users

###
GET http://localhost:8000/users/1

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "lastname": "Dupont",
    "firstname": "Paul",
    "ordinal_number": "48545"
}

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "lastname": "",
    "ordinal_number": "" 
}

###
PUT http://localhost:8000/users/1
Content-Type: application/json

{
    "ordinal_number": "25100"
}

###
DELETE http://localhost:8000/users/2



#####################################################################################



###Look all activities
GET http://localhost:8000/activities

###Look one activity
GET http://localhost:8000/activities/1

### POST Add one activity
POST http://localhost:8000/activities
Content-Type: application/json

{
    "title": "Echographie",
    "description": "L'échographie est une technique d'imagerie employant des ultrasons."
}

### PUT Change one activity
PUT http://localhost:8000/activities/3
Content-Type: application/json

{
    "title": "Médecine générale",
    "description": "Lorem ipsum"
}

###DELETE one activity
DELETE http://localhost:8000/activities/3


####################################################################################


###Look all PurchasesOrders
GET http://localhost:8000/purchasesorders

###Look one PurchasesOrders
GET http://localhost:8000/purchasesorders/1

###POST Add a purchase
POST http://localhost:8000/purchasesorders
Content-Type: application/json

{
    "DVM_id" : "1",
    "quantity": "2"
}


###Look all products
GET http://localhost:8000/products


###POST Add a products
POST http://localhost:8000/products
Content-Type: application/json

{
    "type_logo": "1",
    "film_personnalisé_anesthésie": "1",
    "film_personnalisé_activités": "0",
    "WallOfFame_sticker": "0"
}